export const ExampleOptions = [
  "CARING_AND_EMPATHY",
  "CHARACTER_BUILDING",
  "CARING_AND_EMPATHY",
  "CHARACTER_BUILDING",
  "CARING_AND_EMPATHY",
  "CHARACTER_BUILDING",
  "CARING_AND_EMPATHY",
  "CHARACTER_BUILDING",
  "CARING_AND_EMPATHY",
  "CHARACTER_BUILDING",
];
