export enum siteRoutes {
  login = "/auth/login",
  home = "/",
  dashboard = "/dashboard",
  tabs = "/tabs",
  lectures = "/lectures",
  qa = "/qa",
  banners = "/banners",
  islamicHighlights = "/islamic-highlights",
  hijriEvents = "/hijri-events",
  syncModules = "/sync-modules",
  qasidas = "/qasidas",
  communities = "/communities",
  dhikrTypes = "/dhikr-types",
}
