export const attendeDummyData = [
  {
    id: 1,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    Email: "johndoe@example.com",
    Gender: "Male",
    City: "New York",
    User_Type: ["Attendee", "Host", "Ambassador"],
  },
  {
    id: 2,
    Profile: "https://randomuser.me/api/portraits/women/2.jpg",
    First_Name: "Jane",
    Last_Name: "Smith",
    Email: "janesmith@example.com",
    Gender: "Female",
    City: "New York",
    User_Type: ["Ambassador"],
  },
  {
    id: 3,
    Profile: "https://randomuser.me/api/portraits/men/3.jpg",
    First_Name: "Mike",
    Last_Name: "Johnson",
    Email: "mikej@example.com",
    Gender: "Male",
    City: "New York",
    User_Type: ["Attendee", "Ambassador"],
  },
];

export const HostsDummyData = [
  {
    id: 1,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    Email: "johndoe@example.com",
    Business_Name: "Alpha Enterprises",
    User_Type: ["Attendee", "Host", "Ambassador"],
  },
  {
    id: 2,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    Email: "johndoe@example.com",
    Business_Name: "Alpha Enterprises",
    User_Type: ["Attendee", "Host", "Ambassador"],
  },
  {
    id: 3,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    Email: "johndoe@example.com",
    Business_Name: "Alpha Enterprises",
    User_Type: ["Attendee", "Host", "Ambassador"],
  },
];

export const AmbassadorDummyData = [
  {
    id: 1,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    Email: "johndoe@example.com",
    City: "San Francisco",
    User_Type: ["Attendee", "Host", "Ambassador"],
  },
  {
    id: 2,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    Email: "johndoe@example.com",
    City: "San Francisco",
    User_Type: ["Attendee", "Host", "Ambassador"],
  },
  {
    id: 3,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    Email: "johndoe@example.com",
    City: "San Francisco",
    User_Type: ["Attendee", "Host", "Ambassador"],
  },
];

export const MinorsDummyData = [
  {
    id: 1,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    UserName: "@davidsilbia2",
    ParentName: "Hamza Shahid",
    City: "San Francisco",
  },
  {
    id: 2,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    UserName: "@davidsilbia2",
    ParentName: "Hamza Shahid",
    City: "San Francisco",
  },
  {
    id: 3,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    UserName: "@davidsilbia2",
    ParentName: "Hamza Shahid",
    City: "San Francisco",
  },
];

export const RsvpsDummyData = [
  {
    id: 1,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    Email: "johndoe@example.com",
    RsvpOf: "Steve Smith",
  },
  {
    id: 2,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    Email: "johndoe@example.com",
    RsvpOf: "Steve Smith",
  },
  {
    id: 3,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    Email: "johndoe@example.com",
    RsvpOf: "Steve Smith",
  },
];

export const ManageSubscriptionDummyData = [
  {
    id: 1,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    First_Name: "John",
    Last_Name: "Doe",
    Plan: "Premium",
    Status: "Active",
    Start_Date: "2024-01-10",
    Next_Billing: "2024-04-10",
    Amount: "$49.99",
    Action: "Manage",
  },
  {
    id: 2,
    Profile: "https://randomuser.me/api/portraits/women/2.jpg",
    First_Name: "Jane",
    Last_Name: "Smith",
    Plan: "Standard",
    Status: "Active",
    Start_Date: "2023-12-15",
    Next_Billing: "2024-03-15",
    Amount: "$29.99",
    Action: "Manage",
  },
  {
    id: 3,
    Profile: "https://randomuser.me/api/portraits/men/3.jpg",
    First_Name: "Michael",
    Last_Name: "Brown",
    Plan: "Basic",
    Status: "Expired",
    Start_Date: "2023-06-20",
    Next_Billing: "2023-09-20",
    Amount: "$19.99",
    Action: "Renew",
  },
  {
    id: 4,
    Profile: "https://randomuser.me/api/portraits/women/4.jpg",
    First_Name: "Emily",
    Last_Name: "Davis",
    Plan: "Enterprise",
    Status: "Active",
    Start_Date: "2024-02-01",
    Next_Billing: "2024-05-01",
    Amount: "$99.99",
    Action: "Manage",
  },
  {
    id: 5,
    Profile: "https://randomuser.me/api/portraits/men/5.jpg",
    First_Name: "Chris",
    Last_Name: "Wilson",
    Plan: "Premium",
    Status: "Cancelled",
    Start_Date: "2023-08-05",
    Next_Billing: "2023-11-05",
    Amount: "$49.99",
    Action: "Reactivate",
  },
];

export const EventsDummyData = [
  {
    id: 1,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    Title: "International Digital Art...",
    Location: "San Francisco",
    Date: "14 October, 2025",
    Experience_Type: "Workshop",
    Status: "Active",
  },
  {
    id: 2,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    Title: "International Digital Art...",
    Location: "San Francisco",
    Date: "14 October, 2025",
    Experience_Type: "Workshop",
    Status: "Active",
  },
  {
    id: 3,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    Title: "International Digital Art...",
    Location: "San Francisco",
    Date: "14 October, 2025",
    Experience_Type: "Workshop",
    Status: "Active",
  },
  {
    id: 4,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    Title: "International Digital Art...",
    Location: "San Francisco",
    Date: "14 October, 2025",
    Experience_Type: "Workshop",
    Status: "Active",
  },
  {
    id: 5,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    Title: "International Digital Art...",
    Location: "San Francisco",
    Date: "14 October, 2025",
    Experience_Type: "Workshop",
    Status: "Active",
  },
];

export const CommunitiesDummyData = [
  {
    id: 1,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    Event_Name: "International Digital Art and Cyber Tech Community",
    Created_On: "14 October, 2025",
    Status: "Active",
  },
  {
    id: 2,

    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    Event_Name: "International Digital Art and Cyber Tech Community",
    Created_On: "14 October, 2025",
    Status: "Active",
  },
  {
    id: 3,

    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    Event_Name: "International Digital Art and Cyber Tech Community",
    Created_On: "14 October, 2025",
    Status: "Active",
  },
  {
    id: 4,

    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    Event_Name: "International Digital Art and Cyber Tech Community",
    Created_On: "14 October, 2025",
    Status: "Active",
  },
  {
    id: 5,
    Profile: "https://randomuser.me/api/portraits/men/1.jpg",
    Event_Name: "International Digital Art and Cyber Tech Community",
    Created_On: "14 October, 2025",
    Status: "Active",
  },
];
